name: ui_challenge_1
description: Flutter4fun.com - UI Challenge 1
version: 1.0.0
homepage: https://github.com/imaNNeoFighT/UI-Challenge-1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/
